services:
  prometheus:
    image: prom/prometheus:latest
    container_name: marketplace-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/rules-market.yml:/etc/prometheus/rules/rules-market.yml:ro
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: marketplace-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: marketplace-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_DEFAULT_HOME="/var/lib/grafana/dashboards/dashboard-market.json"
    depends_on:
      - prometheus
      - alertmanager
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana:/var/lib/grafana/dashboards:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: marketplace-node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: marketplace-mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/axiom_market
    ports:
      - "9216:9216"
    restart: unless-stopped
