version: '3.9'

services:
  app:
    build: .
    image: axiom-marketplace:local
    environment:
      - NODE_ENV=production
      - PORT=3002
      - MARKET_PORT=3002
      - MARKET_DB=mongo
      - MARKET_MONGO_URL=mongodb://mongo:27017/axiom_market
      - MEDIA_BACKEND=local
      - MEDIA_LOCAL_DIR=/data/uploads
      - MEDIA_LOCAL_URL_BASE=/uploads/product-media
      - ENABLE_CSP=1
      - FORCE_HTTPS=0
      - TRUST_PROXY_HOPS=1
      - RATE_LIMIT_MAX=200
      - RATE_LIMIT_WINDOW_MS=60000
      - RATE_LIMIT_CART_MAX=100
      - RATE_LIMIT_ORDERS_MAX=60
      - RATE_LIMIT_UPLOAD_MAX=30
      - METRICS_ENABLED=1
    ports:
      - "3002:3002"
    volumes:
      - app_uploads:/data/uploads
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: marketplace-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./infra/monitoring/prometheus/rules-market.yml:/etc/prometheus/rules/rules-market.yml:ro
      - ./infra/monitoring/prometheus/rules-slo.yml:/etc/prometheus/rules/rules-slo.yml:ro
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: marketplace-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./infra/monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    restart: unless-stopped
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: marketplace-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_DEFAULT_HOME="/var/lib/grafana/dashboards/dashboard-market.json"
    depends_on:
      - prometheus
      - alertmanager
    restart: unless-stopped
    volumes:
      - ./infra/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
      - ./infra/monitoring/grafana:/var/lib/grafana/dashboards:ro

  node-exporter:
    image: prom/node-exporter:latest
    container_name: marketplace-node-exporter
    ports:
      - "9100:9100"
    restart: unless-stopped

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: marketplace-mongodb-exporter
    environment:
      - MONGODB_URI=mongodb://mongo:27017/axiom_market
    ports:
      - "9216:9216"
    restart: unless-stopped
    depends_on:
      - mongo

volumes:
  app_uploads:
  mongo_data:
